server:
    port: 8091
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/studentdb?createDatabaseIfNotExist=true
        username: shaya
        password: shaya@123
        driver-class-name: com.mysql.jdbc.Driver
jpa:
    hibernate:
        naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        ddl-auto: update