spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentdb?createDatabaseIfNotExist=true
    username: skshaya
    password: Shaya@1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update